# Generated by Django 6.0.3 on 2026-03-23 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('disciplina', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: P16, HBB - ESCO PEDIATRIA', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('SEG', 'Segunda-feira'), ('TER', 'Terça-feira'), ('QUA', 'Quarta-feira'), ('QUI', 'Quinta-feira'), ('SEX', 'Sexta-feira')], max_length=3)),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('qtd_alunos', models.IntegerField(default=0)),
                ('temas', models.TextField(blank=True, help_text='Temas da simulação ou observações', null=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.professor')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='agendamentos.sala')),
            ],
            options={
                'unique_together': {('dia_semana', 'sala', 'horario_inicio')},
            },
        ),
    ]
