# Generated by Django 6.0.3 on 2026-03-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agendamento',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='data_fim',
            field=models.DateField(blank=True, help_text='Último dia de aula', null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='data_inicio',
            field=models.DateField(blank=True, help_text='Primeiro dia de aula', null=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='temas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='agendamento',
            unique_together={('dia_semana', 'sala', 'horario_inicio', 'data_inicio')},
        ),
    ]
