# Generated by Django 6.0.3 on 2026-03-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_alter_agendamento_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='professor',
            name='disciplina',
        ),
    ]
