# Generated by Django 6.0.3 on 2026-03-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_legenda_remove_professor_disciplina'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Legenda',
        ),
        migrations.AddField(
            model_name='professor',
            name='disciplina',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
