# Generated by Django 6.0.3 on 2026-03-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0004_delete_legenda_professor_disciplina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='disciplina',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='disciplina',
            field=models.CharField(blank=True, help_text='Ex: Semiologia, Pediatria, Urgência', max_length=150, null=True),
        ),
    ]
