# Generated by Django 6.0.3 on 2026-03-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0005_remove_professor_disciplina_agendamento_disciplina'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['dia_semana', 'horario_inicio'], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'ordering': ['nome'], 'verbose_name': 'Professor', 'verbose_name_plural': 'Professores'},
        ),
        migrations.AlterModelOptions(
            name='sala',
            options={'ordering': ['nome'], 'verbose_name': 'Sala', 'verbose_name_plural': 'Salas'},
        ),
        migrations.AlterUniqueTogether(
            name='agendamento',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='esporadica',
            field=models.BooleanField(default=False, help_text='Reservas esporádicas têm prioridade e podem sobrepor reservas regulares.', verbose_name='Reserva Esporádica'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='professores',
            field=models.ManyToManyField(related_name='agendamentos', to='agendamentos.professor'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='salas',
            field=models.ManyToManyField(related_name='agendamentos', to='agendamentos.sala'),
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='sala',
        ),
    ]
